pipeline:
  name: demo-input-set
  identifier: demoinputset
  projectIdentifier: demotestinputsets
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Demo-inputset
        identifier: Demoinputset
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.TestConenctor
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: RunTests
                  name: RunWithTestIntelligence
                  identifier: RunWithTestIntelligence
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    language: Java
                    buildTool: Maven
                    args: test
                    packages: com.nikp
                    runOnlySelectedTests: true
                    preCommand: cd payment-service
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "2"
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Sh
                    command: |-
                      cd payment-service
                      mvn -Dmaven.test.skip=true clean install -X
              - step:
                  type: BuildAndPushDockerRegistry
                  name: pushtoArtifactRegistry
                  identifier: pushtoArtifactRegistry
                  spec:
                    connectorRef: Shruthidockerhub
                    repo: shruthikini/testgitexperience
                    tags:
                      - ShruthiHubb-latest
                    dockerfile: /harness/payment-service/Dockerfile
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
